name: C/C++ CI

on: [push]



jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Installation
      shell: bash
      run: 
        sudo apt install libcsfml-dev
    - uses: actions/checkout@v2
    - name: make fclean
      run: make fclean
    - name: make
      run: make
    - name: make clean
      run: make clean
    - name: RUN
      shell: bash
      run: ./simulation