name: C/C++ CI

on: [push]


runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v2
  - name: Installation
    shell: bash
    run: sudo apt install libcsfml-dev
  - name: make fclean
    run: make fclean
  - name: make
    run: make
  - name: make clean
    run: make clean